"use strict";
/* ---------------- lore: plain-English definitions, offered at the moment of need ------- */
const LORE = {
 "account":"In this trainer, account is shorthand for a platform ad account unless a broader business or reporting scope is named. It sits above campaigns, ad sets or ad groups, ads, and creatives.",
 "platform ad account":"A workspace inside an ad platform, usually beneath a business or administrative container and above campaigns. It can hold permissions, billing, measurement connections, and delivery history; it is not an advertiser, campaign, ad, or creative.",
 "ad":"The delivery object that enters an auction and carries creative. Changing the image, video, or copy changes the creative; it does not automatically create a new account or campaign.",
 "ad set":"A delivery group used by platforms such as Meta to hold audience, placement, schedule, and optimization settings beneath a campaign and above ads.",
 "platform":"The buying system—such as a search, social, or programmatic platform—that runs the auction, enforces policy, and reports attributed results.",
 "paid search":"Auction-based advertising against expressed search intent. Its core controls include keywords, match types, negatives, bids, Quality Score, and impression share.",
 "search intent":"The need or goal implied by a search. It can indicate readiness, research, comparison, support, employment, or another motive; click volume alone does not reveal its value.",
 "ppc":"Pay per click. Often used as shorthand for paid search, although click-priced buying can exist elsewhere too.",
 "paid social":"Auction-based advertising inside social platforms. Creative, audience signals, placements, fatigue, and optimization events usually matter more than keywords.",
 "programmatic":"Automated buying of ad inventory through exchanges, supply platforms, or demand-side platforms. It describes a buying channel and auction path, not a creative format; inventory can include display, native, video, audio, or connected TV.",
 "ctv":"Connected-TV advertising delivered to television screens through streaming inventory. It is a channel and device context, while a CTV spot is the creative made for that context; measurement often leans on reach and modeled view-through outcomes rather than clicks alone.",
 "budget":"An authorization or cap on how much may be spent. It is not the same as delivered media spend, billed cost, cash, or credit.",
 "allocation":"The portion of an available budget assigned to a particular slot, initiative, campaign, or lane. Unspent allocation remains capacity, not cost.",
 "media spend":"Money consumed by ad delivery. Creative production, measurement repair, and policy penalties are operating costs, not media spend.",
 "operations cost":"Non-media investment such as creative production, measurement work, compliance penalties, or portfolio actions. It belongs in all-in business economics but not media-only ROI or CPL.",
 "revenue":"Value recognized by the relevant business model. In this trainer, modeled value, platform-attributed value, settled value, and cash are separate ledgers and should not be substituted for one another.",
 "settled value":"Modeled value whose simulation delay has finished and that has entered the settled-value ledger. In Modes 1–4 it is cash-like reporting value; in Mode 5, receivable collections—not this label—determine actual available cash.",
 "profit":"Value minus the stated cost base for the same scope and window. Profit is an economic result, not necessarily collected cash; modeled profit can remain positive while delayed receivables create a liquidity failure.",
 "modeled contribution":"Modeled earned value minus the media and operating costs included in the displayed scope. It is an amount, while ROI is that profit divided by its cost base; neither is automatically cash.",
 "projected contribution":"Modeled outcome value minus adjusted billed media cost and operations cost for the portfolio window. It is projected because some outcome value may still be modeled or receivable; it is not current cash, ROAS, MER, or ROI.",
 "lead":"A prospective customer action, such as a submitted form or inquiry. A lead is not necessarily accepted, qualified, sold, or converted downstream.",
 "lead quality":"The likelihood that a lead satisfies downstream requirements and creates useful business value. High CTR, conversion volume, or a low CPL does not guarantee high lead quality.",
 "acceptance criteria":"The declared downstream rules used to accept, reject, route, or value a lead after it is created. Criteria can include eligibility, geography, duplication, intent, contactability, or buyer-specific requirements.",
 "downstream acceptance":"The share or outcome of leads that pass the applicable acceptance criteria after acquisition. A change here can reduce realized value even when ad delivery and front-end conversion rates are unchanged.",
 "conversion":"The action the campaign is optimized or evaluated against. It may be a lead, purchase, signup, or another defined business event.",
 "click":"A measurable interaction with an ad. Click volume describes response, not whether the traffic was valuable.",
 "cpc":"Cost per click: media spend divided by clicks. It is driven by auction price and click-through rate, and says nothing by itself about conversion quality.",
 "settlement":"The point when earned modeled value reaches the trainer's settled-value ledger. Settlement delay changes timing, not the day the outcome was earned.",
 "settlement lag":"Time between an earned outcome and its appearance in settled value. Compare metrics using aligned windows before reallocating spend.",
 "unsettled":"Modeled value already earned but not yet settled. It is expected in lag modes and should not be mistaken for a performance collapse.",
 "modeled leads":"The trainer's estimate of underlying lead outcomes for the named scope and window, including leads a platform report may fail to credit. They are simulated business outcomes, not platform claims or cash.",
 "reported lead":"A lead credited by the simulated event source and platform report. Tracking loss can make this lower than modeled leads without changing customer behavior.",
 "reported clicks":"Clicks shown by the simulated platform or measurement path. Tracking anomalies can make them differ from underlying click activity, and click volume alone does not establish lead quality or value.",
 "attribution gap":"The difference between modeled outcomes and platform-attributed claims for the same window. A gap is a measurement diagnostic, not automatic proof of fraud or bad ads.",
 "demand index":"A synthetic multiplier for how much conversion opportunity exists in a period. It moves independently of operator decisions.",
 "learning phase":"A period when a delivery system has limited evidence after launch or a major change. Results can be more volatile while it rebuilds signal.",
 "account learning":"The delivery history and optimization signals associated with a platform ad account or its structures. Changing accounts can change performance even when creative is held constant, but the simulator simplifies behavior that varies by platform and campaign setup.",
 "creative pipeline":"The queue from request or test through build, review, revisions, approval, and readiness to swap into a live ad.",
 "creative test":"A controlled attempt to learn whether a creative idea or variation improves a declared outcome. Testing creates evidence; it does not put an approved asset into delivery automatically.",
 "approval":"Permission for a creative to enter delivery. Approval can concern internal review, rights, or platform policy; those are distinct gates.",
 "compliance hold":"A temporary delivery stop caused by a simulated asset or policy issue. It affects the named scope and is not automatically an account ban.",
 "scaling":"Increasing delivery while watching marginal economics, saturation, fatigue, learning stability, cash, and platform risk—not simply raising every budget.",
 "restate":"A Mode 4 relevance edit that changes geographic framing. It can improve conversion relevance but does not refresh visual attention or reset fatigue.",
 "recast":"A Mode 4 creative change that introduces a new face or treatment and resets attention. It costs more than restating because it replaces the worn presentation.",
 "relevance":"How closely the ad, audience or keyword, offer, and landing experience fit the intended demand. Relevance can improve conversion without creating fresh attention.",
 "slot":"A trainer abstraction that bundles one delivery ad with its active creative, assigned allocation, and—where applicable—platform lane. It is not a universal platform object.",
 "offer timing":"How early a value proposition or call to action appears in a video. If it arrives after most viewers leave, conversion efficiency falls.",
 "campaign budget":"A spending cap attached to a campaign or shared across campaigns, depending on the platform. The trainer may use an account-wide cap for playability and labels that abstraction explicitly.",
 "targeting":"Rules and signals used to determine which eligible people, searches, placements, or contexts can receive an ad.",
 "objective":"The business outcome or learning purpose a campaign is meant to advance. It determines the appropriate scoreboard and decision window.",
 "campaign intent":"The declared role of a campaign, such as immediate acquisition, reach, learning, demand creation, or retargeting. It should be established before performance is judged.",
 "decision window":"The period of evidence considered before a change is made. It should account for volume, volatility, attribution, and settlement delay.",
 "tracking":"The measurement chain that records actions and connects them to advertising. Tracking changes what is reported; it does not create the underlying customer action.",
 "account roi":"Business profit divided by the declared all-in investment for the account and window. It should not be used to name a single winning ad.",
 "ad roi":"Attributed ad value minus media spend, divided by media spend, for a stated ad and time window. It can diverge from business ROI when attribution is incomplete.",
 "all-in business roi":"Modeled earned value minus media and operating costs, divided by those total costs. This is the win metric in Modes 1–4.",
 "attributed media roi":"Platform-attributed earned value minus media spend, divided by media spend. It is a reporting lens, not the all-in win metric.",
 "attributed report":"The trainer lens containing only leads and value credited through its simulated event source and platform rules. It changes reporting, not delivery or customer behavior.",
 "modeled outcome":"The trainer's synthetic business-outcome estimate for the selected window, including outcomes that may lack clean platform attribution.",
 "media cpl":"Media spend divided by modeled leads for the same window. Operating costs are shown separately.",
 "reported media cpl":"Media spend divided by platform-reported leads for the same window. Tracking loss can inflate it without changing the underlying acquisition.",
 "account view":"The modeled-outcome lens: earned business value and leads, including outcomes no platform can tie back to an ad, compared with all-in investment.",
 "ad view":"An older label for the attributed-report lens: only leads and value the event source or platform credits to ads, compared with media spend.",
 "pixel":"A plain-language label for the tracking tag that reports what people do after an ad click or view. A broken tag changes measurement; it does not itself change the simulation's modeled customer outcome.",
 "event source":"One specific measurement input that sends observed events for optimization or reporting, such as a pixel, server feed, app SDK, or offline import. An event source can feed a shared event-source cluster, but the individual source and the cluster are not the same object.",
 "reporting key":"An internal identifier used to route or group events, leads, or attributed results in a reporting system. It can be associated with a user, event source, buyer, or account, but those objects should not be assumed to be interchangeable.",
 "attribution":"The rule and tracking chain used to give an ad credit for an outcome. Account revenue can be real even when attribution cannot prove which ad caused it.",
 "modeled outcome value":"A simulated estimate of business value produced under the trainer's pay-per-validated-outcome contract for a named scope and window. It is the business-outcome ledger—not a platform claim, settled collection, cash balance, profit, MER, ROAS, or ROI.",
 "platform claims":"Conversion value the simulated platforms report for themselves. Cross-platform paths and view-through windows can overlap, so these claims can add up to more than the modeled business value and never create cash by themselves.",
 "cross-account claim":"Platform-attributed value routed to another account through a shared event-source path. It can duplicate or misassign reporting credit, but it does not create another modeled outcome, receivable, collection, or cash entry.",
 "attributed value":"Outcome value that a platform or measurement rule assigns to an advertising touchpoint. It is a number inside an attributed report—not proof of incrementality, another modeled outcome, a receivable, settled value, profit, or cash.",
 "modeled mer":"Modeled Marketing Efficiency Ratio: modeled outcome value divided by media spend for the same initiative and window. It does not subtract media or operating costs, so it is not profit or ROI; modeled value is also not platform-reported credit or collected cash.",
 "blended modeled mer":"Total portfolio modeled outcome value divided by total portfolio media spend for the same window. Blended means the initiatives are combined once without stacking overlapping platform claims. It measures modeled value efficiency, not profit, ROI, liquidity, or cash.",
 "blended mer":"A shorter trainer label for blended modeled MER: portfolio modeled outcome value divided by portfolio media spend, without adding overlapping platform claims.",
 "claimed roas":"Platform-claimed value divided by media spend for the same scope and window. Multiple platforms can claim the same outcome, so claimed ROAS may exceed modeled business efficiency; it is not profit, ROI, incrementality, a receivable, or cash.",
 "receivables":"Modeled value already earned in the simulation but not yet collected as cash. A payout delay moves the due date; it does not erase the modeled outcome.",
 "credit line":"The simulated holding company's shared working-capital facility. It is not a native platform shared-budget feature and it is unrelated to attribution credit.",
 "credit limit":"The maximum simulated balance the shared credit facility can support. It is financing capacity, not cash, budget authorization, media spend, or platform-attributed credit.",
 "available credit":"Credit limit minus bills currently held or used by the shared facility. It is buying headroom for future delivery, not cash, unspent budget, profit, or attribution credit.",
 "adjusted billed cost":"Delivered media cost after the simulation adds billing adjustments and fees. It can be higher than the media-spend number shown by the buying lane.",
 "event-source contamination":"Mixed signals from different simulated advertisers sharing one event-source cluster. It can degrade targeting and route platform claims to the wrong account without creating another modeled outcome.",
 "event-source cluster":"One simulated pool of conversion signals and attribution joins. Multiple platform initiatives for one advertiser can deliberately share it; unrelated verticals sharing it create contamination risk.",
 "signal integrity":"The trainer's 0–100% purity score for an event-source cluster. Lower integrity means more unrelated signal mixing, weaker modeled delivery efficiency, and more cross-account claim risk; it does not mean the underlying customer outcomes vanished.",
 "attribution-control quality":"A portfolio-wide simulation score for audit and reconciliation strength. Raising it narrows future platform-claim uncertainty and supports signal recovery; it does not rewrite historical claims, create outcomes, settle receivables, or add cash.",
 "view-through":"Credit for an outcome after someone saw an ad but did not measurably click it. Useful for reach media, but especially vulnerable to overlap and over-claiming.",
 "business container":"A simulated administrative layer that groups related ad accounts and shared assets. It is above campaigns; changing a creative does not move the account to another business.",
 "advertiser workstream":"One simulated business objective and vertical inside the holding-company mandate. It may run several simultaneous platform initiatives, but concentration and attribution gates still aggregate them as one advertiser.",
 "platform initiative":"A platform-specific ad account and active campaign path inside one advertiser workstream. It owns lane-specific delivery, learning, bids or creative controls; opening one does not create a new advertiser.",
 "workstream mix":"The set of parallel platform initiatives currently serving one advertiser workstream. Adding a lane changes that mix without creating another advertiser or operating company.",
 "buying lane":"A channel-and-platform delivery path with its own auction, targeting, creative, fatigue, demand, and measurement rules. One advertiser can run several parallel initiatives in different lanes.",
 "delivery hierarchy":"The nested delivery objects and their control scope, such as platform ad account → campaign → ad set or ad group → ad → creative. A change at one level does not automatically replace the objects above it.",
 "holding company":"The top simulated portfolio layer in Mode 5. It owns shared cash, credit, risk, and operating constraints across multiple advertiser workstreams.",
 "operating company":"One simulated business represented inside the Mode 5 portfolio. It can have several platform initiatives without becoming several businesses.",
 "cash":"Settled funds available for obligations. Positive modeled economics do not guarantee enough cash when receivables arrive after bills come due.",
 "credit holds":"Adjusted platform bills reserved against the shared simulated credit line until their due dates are paid. They reduce available credit, but they are not cash payments, media budget, or attribution credit.",
 "liquidity":"The ability to meet obligations when they come due using available cash and financing. It is a timing constraint distinct from modeled profitability.",
 "concentration risk":"Exposure created when one platform, advertiser, account, or engine carries too much of a portfolio. A failure in that dependency can then affect the whole system.",
 "platform concentration":"The largest platform family's share of portfolio media spend during the current 30-day gate window. It measures delivery dependency by spend and is distinct from advertiser concentration, which uses modeled outcome value.",
 "advertiser concentration":"The largest advertiser workstream's share of portfolio modeled outcome value during the current 30-day gate window. It measures business-engine dependency by modeled value, not platform spend.",
 "resilience":"Paid or operational capacity that allows delivery and billing to survive a disruption. In Mode 5 it is a simulated portfolio-gate input, not free diversification.",
 "contingency layer":"A paid Mode 5 safety system. The first layer adds billing-grace days; the second also dampens measurement shocks and preserves more learning during lane migration. It is operating capacity, not media spend or a platform feature.",
 "ops action":"One limited daily non-media intervention in Mode 5, such as an audit, creative replacement, mapping repair, or crisis response. Most actions also consume funds, but their cost is operations cost rather than media spend.",
 "acquisition gate":"A Mode 5 checkpoint evaluated after each complete 30-day block. Performance, measurement, liquidity, advertiser concentration, and resilience conditions must all pass together; one failed condition resets the gate streak.",
 "gate streak":"The number of consecutive 30-day acquisition gates that passed every required condition. Any failed gate resets the streak; a strong single day cannot advance it.",
 "crisis":"A Mode 5 operational ticket with a declared scope, cause, and response tradeoff. A creative issue, account hold, event-source problem, and payment failure require different fixes.",
 "account hold":"A delivery block at ad-account level. Swapping a creative cannot repair billing, verification, access, or account-level policy status.",
 "learning":"The trainer's normalized estimate of accumulated delivery signal for the named initiative. The displayed percentage rises as modeled evidence accumulates and can fall after a pause, migration, or structural change; it is a simulator score, not a live platform metric.",
 "algorithm":"The platform system that decides whether, where, and how expensively an ad delivers. In the sim its visible daily mood changes CPM, so volatility becomes a decision instead of invisible dice.",
 "creative rarity":"The trainer's game-like summary of a creative card's modeled upside, scale room, and fatigue risk. Common, Epic, and Legendary are simulator tiers, not industry classifications or guarantees of quality or profit.",
 "common":"The trainer's baseline creative-rarity tier. A Common card can still be profitable; the label describes its modeled range, not its format, production quality, or a guaranteed outcome.",
 "epic":"A less frequent trainer rarity tier with more modeled upside and scale room than Common. It is a game mechanic, not an industry label or a promise that the creative will win.",
 "legendary":"The trainer's rarest creative tier, modeled with the highest breakout upside and greater burnout risk. It is not an industry label or a guarantee of profit.",
 "creative format":"The production and delivery form of a creative—such as static image, native unit, rendered scene, motion graphic, UGC video, explainer, CTV spot, or search text/assets. Format changes lane fit, response, downstream quality, fatigue, and production tradeoffs; it is separate from concept and rarity.",
 "static image":"A single still-image creative. It is usually fast to produce and multiply, with steadier fatigue than person-led motion, but its outcome still depends on concept, audience, placement, and offer.",
 "rendered scene":"An illustrated or 3D creative built to be recast across people, places, colors, sizes, and treatments without a new physical shoot.",
 "motion graphic":"An animated visual or typographic unit. Motion can win attention quickly, while repeated exposure can exhaust the hook faster than a static treatment.",
 "ugc video":"A person-led, platform-native video treatment. It can earn strong attention and breakout scale, but neither the format nor a high rarity guarantees lead quality or profit.",
 "founder / explainer":"A trust-building person-led or narrated explanation. It often trades lower immediate response for stronger downstream fit and slower fatigue.",
 "native display creative":"A deliberately content-like or utilitarian display treatment designed to fit surrounding inventory. It is a creative treatment, while native inventory describes where it runs.",
 "input / ui utility":"A screenshot, form, calculator, bill, quote box, or interface-like creative that makes the next action concrete.",
 "lifestyle static":"A still scene organized around a life event, audience, or place. Relevance and downstream fit normally matter more than raw click rate.",
 "ctv spot":"A full-screen video creative designed primarily for reach and modeled view-through outcomes rather than dependable click response.",
 "search text / assets":"Headlines, descriptions, and eligible search assets matched to expressed intent. Search uses relevance, bids, query demand, and conversion quality rather than social-style rarity.",
 "creative swap":"Replacing the creative carried by an existing ad or trainer slot. The slot keeps its assigned allocation and platform lane; the replacement starts with fresh fatigue and its own economics.",
 "campaign":"A platform delivery container that declares an objective and organizes subordinate delivery objects. Its controls and exact position vary by platform—for example, audience or placement rules may live at campaign, ad-set, ad-group, ad-squad, or line-item level. Changing a creative does not automatically create a new campaign.",
 "ad group":"A search-campaign grouping of related keywords and ads. Tight themes make the relationship among intent, query, ad, and landing experience easier to manage.",
 "keyword":"A paid-search targeting input representing the search intent an advertiser wants to enter. Match behavior, negatives, bids, and relevance shape when it can serve.",
 "bid":"A control expressing how aggressively a buyer competes in an auction. The usable level and unit depend on the channel and bidding strategy; Mode 0 simplifies it to manual Max CPC.",
 "match type":"A paid-search control for how a keyword can relate to a search. Mode 0 uses a deliberately simplified, period-styled 2017 rule set rather than current platform behavior.",
 "exact match":"Mode 0's simplified 2017-style narrow match: the purchased keyword or a close variant. It trades potential volume for tighter intent in this simulation.",
 "phrase match":"Mode 0's simplified 2017-style middle match: the purchased phrase appears in the search. It allows more volume and some additional waste in this simulation.",
 "broad match":"Mode 0's simplified 2017-style wide match: related searches can trigger delivery. It creates the most volume and junk-query risk in this simulation.",
 "negative keyword":"A search term excluded from eligibility. Reviewing actual queries and adding relevant exclusions can reduce wasted clicks.",
 "search terms report":"The searches that actually triggered ads, distinct from the purchased keyword list. It supplies evidence for negatives, structure, and intent diagnosis.",
 "quality score":"A paid-search relevance diagnostic represented as a 1–10 value in Mode 0. The simulation uses it with bids to model rank and cost; it is not a live-platform forecast.",
 "avg position":"A 2017-era placement metric used only by Mode 0. Google retired the live metric in 2019; the trainer retains it to represent the selected period.",
 "max cpc":"The highest click price allowed by Mode 0's simplified manual-bid control. It applies at the simulated ad-group level.",
 "sis":"Search impression share: the portion of eligible search impressions that received an impression. Mode 0 treats it as secondary diagnostic evidence.",
 "impression share":"The portion of eligible impressions that actually received an impression. Search Mode 0 separates the share lost to rank from the share lost to budget because they require different responses.",
 "query ceiling":"The finite amount of eligible search demand available at a given time. Once that ceiling is approached, a larger authorization cannot force additional relevant searches into existence.",
 "sis lost to rank":"Eligible search share missed because simulated bid or relevance was insufficient. Mode 0 responds through bid or relevance rather than budget.",
 "sis lost to budget":"Eligible search share missed because the simulated budget was exhausted. Mode 0 responds through budget rather than bid.",
 "accelerated delivery":"A Mode 0 period-styled pacing choice that spends as quickly as simulated demand permits. It is a historical training mechanic, not guidance about current platform availability.",
 "standard delivery":"Mode 0's period-styled control for pacing a daily budget across the simulated day.",
 "compliance":"The operating discipline that checks policy, claims, disclosures, rights, and usage constraints before and during delivery.",
 "review":"A defined approval or investigation step. Creative review, account review, billing review, and access review affect different scopes and should not be treated as interchangeable.",
 "cpa":"Cost per acquisition — spend divided by conversions. The search-era sibling of CPL.",
 "roas":"Return on ad spend: the declared attributed revenue or value divided by media spend for the same scope and window. A 2.00 ROAS means two units of value per unit spent; it does not subtract cost or prove incrementality.",
 "intake":"The initial operating conversation in which the baseline, objective, measurement source, constraints, decision rights, and expectations are established.",
 "client trust":"A separate relationship scoreboard affected by promises, reporting clarity, expectation management, and whether claims are supported by evidence.",
 "baseline":"The agreed starting level for a metric—for example calls, forms, sales, spend, or acceptance rate—used for comparison. A target can be incremental or ambitious, but its timeframe, evidence, and constraints should be explicit.",
 "in-window":"Inside the stated date range. A campaign can be negative in-window while serving a longer-horizon role, so the phrase should describe timing rather than permanent performance.",
 "band":"A normal diagnostic range for a metric in a particular account and window. It is context for investigation, not automatically a pass/fail threshold.",
 "funnel":"The diagnostic sequence used here: impression, ad click, landing-page visit, on-page click, lead or conversion, then value. Each stage is interpreted beside its denominator and the next stage.",
 "landing-page visit":"An arrival at, or successful load of, the destination page after an ad interaction. It is a separate funnel stage from the ad click and from any action taken on the page.",
 "on-page click":"A click or declared action taken after a landing-page visit, such as opening an offer or continuing a form. It is not the original ad click; LP CTR uses this intermediate action in the trainer.",
 "fatigue":"The loss of response that can occur when the same creative is repeatedly exposed to an audience. The trainer models fatigue as a rising state with format- and rarity-specific effects; real-world pace and symptoms vary.",
 "saturation":"A limit in fresh eligible audience or inventory. Additional budget in the same slot can buy increasingly expensive or lower-quality delivery, causing marginal performance to weaken.",
 "multiplication":"Expanding a promising concept into deliberate variations across useful axes such as hook, audience, geography, offer, size, or treatment. One-variable tests can isolate causality, while structured matrices can explore combinations when the design and volume support them.",
 "axis":"One controlled creative variable, such as colour, geography, size, demographic framing, or offer. Several usable axes make a concept easier to expand methodically.",
 "axes":"Plural of axis: the controlled variables used to create variations of a working concept.",
 "trap":"An ad that looks like a winner on engagement and loses money anyway, usually because its leads are worth little. Slot 3 is one on purpose.",
 "brand play":"Spend evaluated against reach, awareness, demand creation, or a longer decision window rather than immediate attributed profit alone. It may support later efficiency or value, but that effect should be measured rather than assumed; the trainer models this role explicitly.",
 "reach":"How many different people saw it, as opposed to how many times it was shown. Cheap reach is what a brand play is buying.",
 "noise":"Random or unexplained movement that can obscure the effect of a decision. Its size depends on volume, market, metric, and window, so one period is usually weak evidence rather than an automatic reason to act.",
 "variance":"The spread in results caused by randomness rather than a strategy change. Replaying a fixed seed holds the random sequence constant so decision effects are easier to compare.",
 "seed":"The run number in the corner. It fixes every random roll, so the same seed replayed means a better result came from a better decision.",
 "matrix":"One idea built out across every combination of its variables — five colours by five states is a 25-asset matrix.",
 "cut":"A version of a creative made for one slice: a state cut, a language cut, a 16x9 cut. Same story, re-pointed.",
 "native":"Ad inventory designed to sit within the surrounding content experience. Plain or content-like creative can fit that context, but performance still depends on placement, message, audience, offer, and downstream quality.",
 "demand gen":"A visual Google advertising lane represented in the trainer as interruption or demand-stimulation media rather than expressed search intent. The simulator uses stylized delivery physics, not a live-platform benchmark.",
 "display":"Visual ad inventory across websites and apps, commonly bought directly or programmatically. Pricing and quality vary widely, so evaluate viewability, response, conversion quality, cost per outcome, and attribution rather than assuming impressions are cheap.",
 "audience":"The group of people an ad is aimed at.",
 "demo":"Short for demographic — the slice of people a version is cast for, like seniors or 35-plus.",
 "vertical":"The product line an ad sells, for example auto or home.",
 "concept":"The idea behind an ad — the scene, the mechanic, the promise. One concept can become dozens of assets.",
 "creative":"The customer-facing image, video, copy, audio, or asset combination carried by an ad. The ad is the delivery object; the creative is what people experience.",
 "asset":"One deliverable file at one size. A concept is an idea; an asset is a file.",
 "hook":"The first beat that stops the scroll — the thing that earns the second of attention.",
 "mechanic":"The repeatable device a concept runs on: a bill screenshot, a price reveal, a street scene. Mechanics travel between concepts.",
 "placement":"Where the ad actually ran. The same creative in two placements can perform very differently.",
 "tail":"The long list of small ads under the handful that carry the account.",
 "decay":"A winner slowly getting worse as it fatigues or its audience saturates.",
 "milking":"Running a proven ad for the profit it still makes while not expecting it to grow.",
 "geo cut":"A creative version adapted for a place such as a state, county, city, or region. Geographic relevance can help when the market, offer, and message support it, but it is not a universal performance multiplier.",
 "broad":"No targeting narrowing, and no single place — the version that runs everywhere.",
 "front end":"The cheap-clicks half of the funnel: CPM, CTR, cost per click.",
 "lander":"The page an ad sends people to. LP CTR measures the lander's pull, not the ad's.",
 "cpm":"Cost per thousand impressions — what it costs to be seen.",
 "ctr":"Click-through rate: clicks divided by impressions. Attention, not value.",
 "cvr":"Conversion rate: completed conversion events divided by the stated eligible denominator. In Modes 1–4, the displayed CVR is leads divided by ad clicks; other systems may use visits, sessions, or users.",
 "cpl":"Cost per lead: the declared cost base divided by leads in the same window. The interface labels whether the cost base is media-only or all-in.",
 "landing-page optimization":"A future-facing Mode 1–4 action that improves the simulated landing step. Each application raises LP CTR by five points and overall click-to-lead CVR by eight percent, up to two applications.",
 "epl":"Earnings or value per lead: the declared earned value divided by leads for the same scope and window. It belongs beside CPL, acceptance, and settlement timing; no single metric captures the whole business.",
 "lp ctr":"The share of people already on the landing page who clicked through on it.",
 "roi":"Return on investment: profit divided by the declared investment for the same scope and window. The cost base and value window must be stated; account ROI and ad ROI can therefore answer different questions.",
 "impressions":"How many times the ad was shown."
};
const KNOWLEDGE_DB=Object.freeze({
  version:2,
  note:"The former numbered references now resolve into this neutral in-app learning database. It combines documented simulator mechanics with the supplied analogy framework; period-specific and simulator-only rules are labeled as such.",
  lessons:[
    {id:"01",title:"Creative architecture",summary:"Separate the idea, execution, and deliverable so successful advertising can be expanded deliberately.",
      foundation:"A concept is the central idea. A mechanic is the repeatable device that expresses it. A hook earns attention. Creative is what the audience experiences; an asset is one finished file.",
      working:"Document each concept's usable axes—audience, geography, offer, format, size, treatment, or opening hook. Build cuts and matrices from proven concepts instead of treating every asset as a new idea.",
      expert:"A useful creative system preserves the winning mechanism while isolating meaningful variables. Tests that change several axes at once can create lift without revealing which change caused it.",
      checklist:["Name the concept and mechanic.","Identify the hook and intended audience.","Record which axis each variation changes.","Keep concept-level and asset-level results separate."],
      terms:["concept","mechanic","hook","creative","asset","cut","matrix","axis","placement"]},
    {id:"02",title:"Iteration, fatigue, and saturation",summary:"Expand proven ideas while distinguishing worn-out creative from exhausted audience capacity.",
      foundation:"Fatigue means the same creative has lost attention. Saturation means the available audience or inventory has become expensive to reach. They are related but require different responses.",
      working:"A creative test creates an option; a creative swap puts that option into delivery. Restating can improve relevance without refreshing attention, while recasting or replacing creative resets fatigue.",
      expert:"Scaling should follow marginal economics rather than headline averages. Creative decay, audience overlap, auction pressure, and rapid structural changes can make the next unit of spend less valuable than the previous one.",
      checklist:["Diagnose fatigue separately from saturation.","Keep replacement creative ready before burnout.","Scale in measured steps.","Compare marginal performance after each change."],
      terms:["creative test","creative swap","creative rarity","common","epic","legendary","fatigue","saturation","decay","multiplication","restate","recast","scaling"]},
    {id:"03",title:"Purpose before scoreboard",summary:"Performance only becomes meaningful when the campaign's purpose and measurement scope are known.",
      foundation:"A campaign can be designed for immediate profit, learning, reach, demand creation, or conversion. Negative in-window profit does not automatically mean it failed.",
      working:"Modeled outcome compares earned business value with all-in investment. Attributed report compares platform-creditable value with media spend. They answer different questions and must keep their windows and cost bases visible.",
      expert:"Portfolio roles should be evaluated against intended contribution and decision horizon. Incrementality, downstream effects, attribution loss, and learning value can matter even when a platform report looks weak.",
      checklist:["State the objective.","Confirm the evaluation window.","Identify the measurement lens and cost base.","Ask what the spend is intended to accomplish before changing it."],
      terms:["objective","campaign intent","account view","ad view","account roi","ad roi","brand play","learning","in-window","reach","profit"]},
    {id:"04",title:"Funnel diagnosis",summary:"Read performance as a sequence so the location of a problem is clear before an intervention is chosen.",
      foundation:"The trainer's diagnostic path is impression → click → landing-page visit → on-page action → lead or conversion → value. Each rate must name its numerator and denominator.",
      working:"CPM prices exposure, CTR measures ad response, LP CTR measures an intermediate landing-page action, and the displayed CVR remains overall clicks-to-leads. LP CTR is diagnostic; it is not multiplied into CVR a second time. CPL combines upstream media cost and the lead outcome.",
      expert:"Aggregate rates can hide changes in traffic mix, placement, lead quality, downstream acceptance, settlement, or lead value. Diagnose both the rate and denominator, then segment only when enough volume exists. The landing-step action in Modes 1–4 is an explicit future-facing training intervention, not a passive extra funnel multiplier.",
      checklist:["Find the first stage that changed materially.","Check its denominator and volume.","Compare the stages before and after the break.","Do not repair a landing-page problem with a creative change."],
      terms:["funnel","impressions","click","landing-page visit","on-page click","lead","lead quality","acceptance criteria","downstream acceptance","conversion","cpm","ctr","lp ctr","cvr","cpl","lander"]},
    {id:"05",title:"Signal, noise, and decision windows",summary:"Separate persistent movement from ordinary volatility before reallocating budget.",
      foundation:"Daily results move even when strategy is unchanged. One favorable or unfavorable period is weak evidence by itself.",
      working:"Use recent movement, adequate conversion volume, settled outcomes, and the account's normal band before acting. A fixed seed holds the random sequence constant so decisions can be compared fairly.",
      expert:"A decision window should reflect conversion delay, seasonality, auction volatility, effect size, and acceptable error. A longer window reduces noise but can react too slowly to a genuine break.",
      checklist:["Check whether outcomes have settled.","Compare several periods rather than one.","Confirm volume supports the conclusion.","Record the hypothesis before changing allocation."],
      terms:["noise","variance","seed","settlement lag","decision window","band"]},
    {id:"06",title:"Metric fluency",summary:"Use each metric for the question it can answer and preserve the correct denominator.",
      foundation:"CTR measures attention, CPL and CPA measure acquisition cost, EPL measures value per lead, ROI measures profit relative to cost, and ROAS measures value relative to media spend.",
      working:"A high CTR can coexist with poor economics. CPL belongs beside EPL or conversion value. Modeled MER is modeled value divided by media spend; ROAS is attributed or claimed value divided by media spend; neither subtracts cost. Contribution is an amount, while ROI divides profit by its stated cost base.",
      expert:"Reported metrics depend on attribution rules, timing, cohort maturity, aggregation level, and cost scope. Modeled outcome value, platform claims, projected contribution, settled value, receivables, and cash can all differ while remaining internally consistent. Platform claims should not be added as if each platform created a separate outcome.",
      checklist:["Name the numerator and denominator.","Confirm scope and date window.","Label modeled, claimed, settled, or collected value.","Pair cost with outcome quality.","Do not substitute engagement for business value."],
      terms:["media spend","revenue","settled value","profit","modeled contribution","projected contribution","roi","roas","claimed roas","modeled mer","blended modeled mer","cpl","cpa","epl","platform claims"]},
    {id:"07",title:"Measurement and attribution",summary:"Treat tracking as evidence about outcomes, not as the system that creates those outcomes.",
      foundation:"A pixel or event source reports actions after ad exposure. Attribution applies rules that assign credit. A tracking failure can change reported results without changing customer behavior.",
      working:"When modeled and attributed totals diverge, inspect tracking, reporting-key routing, and attribution before pausing ads. Repair affects future reporting; it does not rewrite the historical gap.",
      expert:"Cross-platform paths, view-through windows, delayed events, duplicated claims, consent loss, and event-source contamination can produce incompatible reports. Reconciliation separates modeled outcomes, cross-account claims, settled value, receivables, cash, and platform claims without rewriting history.",
      checklist:["Compare modeled with attributed totals.","Check event health and settlement timing.","Identify the attribution rule and window.","Do not manufacture value by summing overlapping claims."],
      terms:["pixel","tracking","reporting key","attribution","modeled outcome value","platform claims","cross-account claim","view-through","attribution gap","event-source contamination","signal integrity","attribution-control quality","settlement","settled value"]},
    {id:"08",title:"Discovery and operating context",summary:"Establish the business objective, baseline, constraints, and decision rights before optimizing media.",
      foundation:"The same dashboard can represent an in-house team, agency relationship, lead-generation account, growth mandate, or brand program. Context changes what success means.",
      working:"An intake should establish baseline, target, source of truth, evaluation window, budget authority, platform scope, creative process, and communication cadence. Trust and performance remain separate scoreboards.",
      expert:"Strong operating agreements define who can change budgets, approve creative, interpret attribution, accept risk, and stop delivery. Clear escalation paths reduce analytical and organizational errors.",
      checklist:["Record the baseline and objective.","Agree on the source of truth.","Clarify decision rights and constraints.","Document unanswered questions and owners."],
      terms:["intake","baseline","client trust","budget","approval","tracking"]},
    {id:"09",title:"Channel and platform physics",summary:"Choose controls that match how each buying channel finds and converts demand.",
      foundation:"Paid search captures expressed intent. Paid social, display, and Demand Gen interrupt or stimulate demand. Programmatic and CTV can emphasize reach and view-through measurement.",
      working:"Search uses keywords, bids, match types, negatives, Quality Score, and finite query volume. Social and visual channels depend more on audience, creative, fatigue, and auction delivery.",
      expert:"Channel interactions include branded-search lift, audience overlap, impression-share ceilings, auction inflation, view-through uncertainty, and concentration risk. Platform behavior here is training physics, not a live benchmark.",
      checklist:["Classify the lane as intent, interruption, or reach-led.","Use lane-appropriate controls and metrics.","Check demand ceilings and overlap.","Separate simulator assumptions from platform evidence."],
      terms:["paid search","ppc","paid social","programmatic","ctv","display","demand gen","view-through","account learning","audience","keyword","match type","quality score","sis"]},
    {id:"10",title:"Structure, portfolio, and liquidity",summary:"Identify the operational layer being changed and distinguish profitable economics from available cash.",
      foundation:"One hierarchy used in the trainer is platform ad account → campaign → ad set or ad group → ad → creative. A trainer slot bundles an ad with creative; swapping creative does not create a new account or campaign. A buying lane describes the channel path, not another hierarchy level.",
      working:"Portfolio mode adds business containers, advertiser workstreams, workstream mixes, platform initiatives, event-source clusters, shared budget, receivables, credit holds, and ops actions. Each control names the layer it changes and the resources it consumes.",
      expert:"Positive projected contribution can coexist with liquidity failure when collections lag adjusted bills. Available credit, cash, modeled value, and profit answer different questions. Shared credit and event sources create cross-account risk that isolated campaign metrics cannot reveal.",
      checklist:["Name the hierarchy level being changed.","Separate authorization, spend, billed cost, contribution, and cash.","Track receivable and available-credit timing.","Compare platform and advertiser concentration using the correct denominator.","Check shared-system effects before an account-level fix."],
      terms:["account","platform ad account","campaign","ad set","ad group","ad","slot","delivery hierarchy","buying lane","platform initiative","advertiser workstream","workstream mix","business container","holding company","operating company","budget","allocation","credit line","credit limit","available credit","credit holds","receivables","cash","liquidity","platform concentration","advertiser concentration","resilience","contingency layer","ops action","acquisition gate","gate streak"]},
    {id:"11",title:"Asset rights, policy, and review",summary:"Treat inspection and approval as media operations, not as a final cosmetic check.",
      foundation:"An effective asset can still be unusable because of third-party branding, recognizable people, unsupported claims, missing disclosures, or platform policy.",
      working:"Inspect source, rights, likeness, visible marks, pricing language, promises, and required disclosures before shipping. Advanced modes add build time, review, revisions, rejection, holds, and replacement planning.",
      expert:"A mature workflow preserves provenance, approval history, usage scope, expiration, substantiation, and platform-specific policy notes. Creative rejection, account restriction, billing hold, and business access failure are distinct incidents.",
      checklist:["Verify source and usage rights.","Check people, brands, claims, prices, and disclosures.","Record approval status and limitations.","Keep alternate compliant creative ready."],
      terms:["compliance","review","approval","account hold","asset","creative pipeline"]}
  ]
});
const KNOWLEDGE_BY_ID=Object.freeze(Object.fromEntries(KNOWLEDGE_DB.lessons.map(lesson=>[lesson.id,lesson])));
const LESSON_SCOPE=Object.freeze({
  "01":"General creative-system concepts; examples use trainer vocabulary.",
  "02":"General iteration concepts plus explicitly labeled Modes 1–4 fatigue, saturation, Restate, and Recast mechanics.",
  "03":"General objective-setting and measurement-scope practice; trainer win gates remain simulator-specific.",
  "04":"General funnel diagnosis with the trainer's explicit clicks-to-leads CVR and landing-step intervention.",
  "05":"General evidence-window practice; fixed seeds and volatility ranges are simulator mechanics.",
  "06":"General metric definitions with trainer-specific cost and value ledgers called out by name.",
  "07":"General measurement concepts plus simulated attribution and settlement systems.",
  "08":"General agency and in-house operating practice; no particular person or organization is assumed.",
  "09":"General channel distinctions plus a simplified 2017 search model in Mode 0; live platform controls can differ.",
  "10":"General hierarchy and liquidity concepts expressed through Mode 5's fully simulated portfolio system.",
  "11":"General rights, policy, and review workflow; simulated holds and penalties are not platform policy predictions."
});
const PRIMARY_LESSON_TERMS=Object.freeze({
  "01":["concept","mechanic","hook","creative","asset","creative format","static image","rendered scene","motion graphic","ugc video","founder / explainer","native display creative","input / ui utility","lifestyle static","ctv spot","search text / assets","cut","matrix","axis","axes","multiplication","geo cut","demo","placement"],
  "02":["creative test","creative swap","fatigue","saturation","decay","milking","scaling","restate","recast","creative rarity","common","epic","legendary","tail","trap","offer timing"],
  "03":["objective","campaign intent","account view","ad view","account roi","ad roi","all-in business roi","attributed media roi","attributed report","modeled outcome","brand play","in-window","reach"],
  "04":["funnel","impressions","click","reported clicks","landing-page visit","on-page click","lead","modeled leads","lead quality","acceptance criteria","downstream acceptance","conversion","reported lead","cpm","ctr","cvr","cpl","media cpl","reported media cpl","lander","lp ctr","landing-page optimization","front end"],
  "05":["noise","variance","seed","decision window","band","settlement lag"],
  "06":["media spend","operations cost","revenue","settled value","profit","modeled contribution","projected contribution","cpc","cpa","epl","roi","roas","claimed roas","modeled mer","blended modeled mer","blended mer"],
  "07":["pixel","event source","tracking","reporting key","attribution","modeled outcome value","platform claims","cross-account claim","attributed value","view-through","attribution gap","event-source contamination","event-source cluster","signal integrity","attribution-control quality","settlement","unsettled"],
  "08":["intake","baseline","client trust"],
  "09":["platform","paid search","search intent","ppc","paid social","programmatic","ctv","display","demand gen","native","audience","targeting","relevance","keyword","bid","match type","exact match","phrase match","broad match","negative keyword","search terms report","quality score","avg position","max cpc","sis","impression share","query ceiling","sis lost to rank","sis lost to budget","accelerated delivery","standard delivery","algorithm","learning","learning phase","account learning","demand index","broad"],
  "10":["account","platform ad account","campaign","ad set","ad group","ad","slot","delivery hierarchy","buying lane","platform initiative","advertiser workstream","workstream mix","business container","holding company","operating company","budget","allocation","campaign budget","cash","credit line","credit limit","available credit","credit holds","receivables","adjusted billed cost","liquidity","concentration risk","platform concentration","advertiser concentration","resilience","contingency layer","ops action","acquisition gate","gate streak","crisis","vertical"],
  "11":["compliance","review","approval","compliance hold","account hold","creative pipeline"]
});
const PRIMARY_LESSON_BY_TERM=Object.freeze(Object.fromEntries(Object.entries(PRIMARY_LESSON_TERMS)
  .flatMap(([id,terms])=>terms.map(term=>[term,id]))));
function lessonForTerm(term){
  const key=String(term||"").toLowerCase();
  return KNOWLEDGE_BY_ID[PRIMARY_LESSON_BY_TERM[key]||"06"];
}

const LORE_KEYS=Object.keys(LORE).sort((a,b)=>b.length-a.length);
const LORE_ALIAS_TO_KEY={};
const addLoreAlias=(alias,key)=>{if(alias&&LORE[key])LORE_ALIAS_TO_KEY[String(alias).toLowerCase()]=key;};
LORE_KEYS.forEach(key=>addLoreAlias(key,key));
Object.entries({
  accounts:"account",ads:"ad","ad sets":"ad set","ad groups":"ad group",slots:"slot",platforms:"platform",campaigns:"campaign",
  budgets:"budget",allocations:"allocation",keywords:"keyword",bids:"bid","match types":"match type",
  "negative keywords":"negative keyword","search-terms report":"search terms report","search-term report":"search terms report",
  creatives:"creative",assets:"asset",concepts:"concept",mechanics:"mechanic",hooks:"hook",matrices:"matrix",
  "creative formats":"creative format","static images":"static image","rendered scenes":"rendered scene",
  "motion graphics":"motion graphic","ugc videos":"ugc video","founder explainer":"founder / explainer",
  "native display":"native display creative","utility creative":"input / ui utility","lifestyle statics":"lifestyle static",
  "ctv spots":"ctv spot","search assets":"search text / assets",
  "common tier":"common","common rarity":"common","epic tier":"epic","epic rarity":"epic","legendary tier":"legendary","legendary rarity":"legendary",
  cuts:"cut",placements:"placement",audiences:"audience",verticals:"vertical",pixels:"pixel",clicks:"click",leads:"lead",
  conversions:"conversion",workstreams:"advertiser workstream","advertiser workstreams":"advertiser workstream",
  "platform initiatives":"platform initiative","business containers":"business container","holding companies":"holding company",
  "operating companies":"operating company",receivable:"receivables","operating costs":"operations cost",
  "workstream mixes":"workstream mix","buying lanes":"buying lane","platform lane":"buying lane","platform lanes":"buying lane",
  "lane physics":"buying lane","real hierarchy":"delivery hierarchy","delivery hierarchies":"delivery hierarchy",
  "landing page optimization":"landing-page optimization","landing-page optimizations":"landing-page optimization",
  "landing page visit":"landing-page visit","landing page visits":"landing-page visit","landing-page visits":"landing-page visit",
  "lp visit":"landing-page visit","lp visits":"landing-page visit","on page click":"on-page click","on page clicks":"on-page click","on-page clicks":"on-page click",
  "event source cluster":"event-source cluster","event source clusters":"event-source cluster",
  "event sources":"event source","credit hold":"credit holds","locked credit":"credit holds","campaign budgets":"campaign budget",
  "reporting keys":"reporting key","lead-quality":"lead quality","acceptance criterion":"acceptance criteria",
  "downstream acceptance criteria":"acceptance criteria","connected tv":"ctv","connected television":"ctv","programmatic buying":"programmatic",
  "search intents":"search intent","impression shares":"impression share","query ceilings":"query ceiling",
  "attributed reports":"attributed report","modeled outcomes":"modeled outcome","modeled outcome values":"modeled outcome value","concentration risks":"concentration risk",
  workstream:"advertiser workstream",initiative:"platform initiative",
  "operating cost":"operations cost","platform claim":"platform claims","claimed value":"platform claims","modeled value":"modeled outcome value",
  "modeled revenue":"modeled outcome value","modeled revenues":"modeled outcome value","cross-tag contamination":"event-source contamination",
  "attributed values":"attributed value","daily budget":"budget","account budget":"budget",
  "simulation cap":"budget","portfolio authorization":"budget","search account":"platform ad account","ad account":"platform ad account",
  "ad accounts":"platform ad account","platform account":"platform ad account","platform accounts":"platform ad account","search impression share":"impression share","lost to rank":"sis lost to rank",
  "lost to budget":"sis lost to budget","compliance flag":"compliance hold","compliance flags":"compliance hold",
  "account-level hold":"account hold","account-level holds":"account hold",
  "creative fatigue":"fatigue","audience saturation":"saturation","learning state":"learning","learning score":"learning","learning percentage":"learning",
  "modeled lead":"modeled leads","reported leads":"reported lead","measurable clicks":"reported clicks",
  "settled values":"settled value","modeled contributions":"modeled contribution","portfolio contribution":"projected contribution","projected contributions":"projected contribution",
  mer:"modeled mer","modeled mers":"modeled mer","modeled marketing efficiency ratio":"modeled mer","marketing efficiency ratio":"modeled mer",
  "blended marketing efficiency ratio":"blended modeled mer","platform-claimed roas":"claimed roas","platform claimed roas":"claimed roas","reported roas":"claimed roas",
  "credit facility":"credit line","credit limits":"credit limit","available credits":"available credit","buying headroom":"available credit","adjusted bill":"adjusted billed cost","adjusted bills":"adjusted billed cost",
  "simulated integrity":"signal integrity","simulated signal integrity":"signal integrity","event-source integrity":"signal integrity","event source integrity":"signal integrity","claim purity":"signal integrity",
  "simulated attribution-control quality":"attribution-control quality","attribution control quality":"attribution-control quality","audit quality":"attribution-control quality",
  "cross-account claims":"cross-account claim","cross account claim":"cross-account claim","cross account claims":"cross-account claim","claim gap":"attribution gap",
  "platform concentrations":"platform concentration","advertiser concentrations":"advertiser concentration","advertiser risk":"advertiser concentration",
  "contingency layers":"contingency layer","billing grace":"contingency layer","billing-grace days":"contingency layer",
  "ops actions":"ops action","operations action":"ops action","operations actions":"ops action","operational action":"ops action","operational actions":"ops action",
  "acquisition gates":"acquisition gate","portfolio gate":"acquisition gate","portfolio gates":"acquisition gate","portfolio qualification gate":"acquisition gate","gate streaks":"gate streak",
  crises:"crisis","operational crises":"crisis",qs:"quality score",negatives:"negative keyword","avg pos":"avg position"
}).forEach(([alias,key])=>addLoreAlias(alias,key));
const LORE_ALIASES=Object.keys(LORE_ALIAS_TO_KEY).sort((a,b)=>b.length-a.length);
const LORE_RX=new RegExp("(^|[^\\w-])("+LORE_ALIASES.map(k=>k.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|")+")(?![\\w-])","gi");
const LORE_SEL=".prose, .verdict, .funnel, .note, .fam, .binrow .nm, .eventtitle, .eventbody, .reality-copy, .section-head, .stat .k, .stat .sub, .grid2, .config .hint, .rosetta .flow, .guide-depth, .eyebrow, .matrix, .pixelrow, .tag, .portfolio-banner";
